{application,consilium,
             [{description,"consilium"},
              {vsn,"1"},
              {modules,[consilium,consilium_app,consilium_resource,
                        consilium_sup]},
              {registered,[]},
              {applications,[kernel,stdlib,inets,crypto,mochiweb,webmachine]},
              {mod,{consilium_app,[]}},
              {env,[]}]}.
